// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "NgramService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::ais;

class NgramServiceHandler : virtual public NgramServiceIf {
 public:
  NgramServiceHandler() {
    // Your initialization goes here
  }

  void lm(std::vector<PrintTextStats> & _return, const std::vector<std::string> & src) {
    // Your implementation goes here
    printf("lm\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<NgramServiceHandler> handler(new NgramServiceHandler());
  shared_ptr<TProcessor> processor(new NgramServiceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

